// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-bookings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-bookings.ts
var list_bookings_default = defineTool({
  name: "list_bookings",
  title: "List bookings",
  description: "List the signed-in business's bookings, optionally filtered by date range and status.",
  inputSchema: {
    from: z.string().describe("Start date (YYYY-MM-DD), inclusive.").optional(),
    to: z.string().describe("End date (YYYY-MM-DD), inclusive.").optional(),
    status: z.string().describe("Booking status filter, e.g. pending, confirmed, cancelled, completed.").optional(),
    limit: z.number().int().describe("Maximum rows to return (default 50, max 200).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select(
      "id, booking_date, booking_time, duration_minutes, client_name, client_email, service, status, payment_status, service_price, party_size, notes, assigned_employee_id"
    ).order("booking_date", { ascending: true }).order("booking_time", { ascending: true }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (from) query = query.gte("booking_date", from);
    if (to) query = query.lte("booking_date", to);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-booking.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_booking_default = defineTool2({
  name: "create_booking",
  title: "Create booking",
  description: "Create a new booking for the signed-in business. Times use 24h HH:MM and dates use YYYY-MM-DD.",
  inputSchema: {
    client_name: z2.string().describe("Customer name."),
    booking_date: z2.string().describe("Booking date, YYYY-MM-DD."),
    booking_time: z2.string().describe("Booking start time, 24h HH:MM."),
    service: z2.string().describe("Service name for this booking."),
    duration_minutes: z2.number().int().describe("Duration in minutes (default 30).").optional(),
    client_email: z2.string().describe("Customer email address.").optional(),
    notes: z2.string().describe("Internal notes for this booking.").optional(),
    party_size: z2.number().int().describe("Number of people, for table/group bookings.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bookings").insert({
      user_id: ctx.getUserId(),
      client_name: input.client_name,
      client_email: input.client_email ?? null,
      booking_date: input.booking_date,
      booking_time: input.booking_time,
      service: input.service,
      duration_minutes: input.duration_minutes ?? 30,
      notes: input.notes ?? null,
      party_size: input.party_size ?? null,
      status: "confirmed"
    }).select("id, booking_date, booking_time, client_name, service, status");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { booking: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/update-booking-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var update_booking_status_default = defineTool3({
  name: "update_booking_status",
  title: "Update booking status",
  description: "Change the status of one of the signed-in business's bookings (e.g. confirmed, cancelled, completed).",
  inputSchema: {
    booking_id: z3.string().describe("The booking id to update."),
    status: z3.string().describe("New status: pending, confirmed, cancelled, completed, or no_show."),
    decline_reason: z3.string().describe("Optional reason shown when cancelling.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ booking_id, status, decline_reason }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bookings").update({ status, ...decline_reason ? { decline_reason } : {} }).eq("id", booking_id).select("id, status, booking_date, booking_time, client_name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return {
        content: [{ type: "text", text: "No booking found with that id for your account." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { booking: data[0] }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool4({
  name: "list_clients",
  title: "List clients",
  description: "List the signed-in business's saved clients, optionally filtered by a name or email search.",
  inputSchema: {
    search: z4.string().describe("Case-insensitive text to match against name or email.").optional(),
    limit: z4.number().int().describe("Maximum rows to return (default 50, max 200).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, name, email, phone, notes, created_at").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (search) {
      const term = search.replace(/[%,]/g, " ").trim();
      if (term) query = query.or(`name.ilike.%${term}%,email.ilike.%${term}%`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_services_default = defineTool5({
  name: "list_services",
  title: "List services",
  description: "List the services the signed-in business offers, with duration and price.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("services").select("id, name, duration_minutes, price, active, sort_order").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-staff.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_staff_default = defineTool6({
  name: "list_staff",
  title: "List staff",
  description: "List the signed-in business's team members and their availability status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("employees").select("id, name, email, position, available_now, manual_status, auth_user_id, created_at").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const staff = (data ?? []).map((e) => ({ ...e, invite_pending: !e.auth_user_id }));
    return {
      content: [{ type: "text", text: JSON.stringify(staff) }],
      structuredContent: { staff }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rehafgjaqbdeuatnfiyk";
var mcp_default = defineMcp({
  name: "booksuite-your-all-in-one-solution",
  title: "BookSuite: Your All-in-One Solution",
  version: "0.1.0",
  instructions: "Tools for BookSuite, a booking platform for service businesses. All tools act as the signed-in business owner or staff member. Use `list_bookings` to read the schedule, `create_booking` to add an appointment, `update_booking_status` to confirm or cancel one, and `list_clients`, `list_services`, and `list_staff` to read the business's customers, service menu, and team.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_bookings_default,
    create_booking_default,
    update_booking_status_default,
    list_clients_default,
    list_services_default,
    list_staff_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
